environment:
  CLI_VERSION: 3.1.301
image: Visual Studio 2019
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 14
  - yarn --cache-folder=.cache/yarn --no-progress --pure-lockfile
  - cinst fake
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - if not defined RUSTFLAGS rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
cache:
  - .cache/yarn
build_script:
  - cmd: build.cmd -t CopyBinaries
test: off
test_script:
  - yarn test
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
